# Theory of Computation - Assignment 4: Check if a given string is from the language generated by Reg Exp: (0 U 10)* 1*
# Name: Deva Surya Vivek

import sys


class FiniteAutomata:
    # machine object
    def __init__(self, num_of_states):
        self.final_states = [False] * num_of_states
        self.transitions = [{} for i in range(num_of_states)]

    def state_transition(self, source_state, input_bit, target_state):
        self.transitions[source_state][input_bit] = target_state

    def make_final_state(self, state):
        self.final_states[state] = True


if len(sys.argv) == 2:
    file_name = sys.argv[1]
    input_lines = [line.rstrip('\n') for line in open(file_name)]
    if not input_lines:
        input_string = ""
    else:
        input_string = input_lines[0]

    print("The input string is: " + input_string)

    if input_string != "":

        length = len(input_string)

        # Creating a machine for Reg Exp: (0 U 10)* 1*
        finite_automata = FiniteAutomata(4)
        finite_automata.state_transition(0, 0, 0)  # q0 -- 0 --> q0
        finite_automata.state_transition(0, 1, 1)  # q0 -- 1 --> q1
        finite_automata.state_transition(1, 0, 0)  # q1 -- 0 --> q0
        finite_automata.state_transition(1, 1, 2)  # q1 -- 1 --> q2
        finite_automata.state_transition(2, 0, 3)  # q2 -- 0 --> q3
        finite_automata.state_transition(2, 1, 2)  # q2 -- 1 --> q2
        finite_automata.state_transition(3, 0, 3)  # q3 -- 0 --> q3
        finite_automata.state_transition(3, 1, 3)  # q3 -- 0 --> q3
        finite_automata.make_final_state(0)
        finite_automata.make_final_state(1)
        finite_automata.make_final_state(2)

        current_state = 0
        is_string_valid = False

        try:
            for bit in input_string:
                bit = int(bit)
                current_state = finite_automata.transitions[current_state][bit]
            is_string_valid = finite_automata.final_states[current_state]
        except KeyError:
            is_string_valid = False
    else:
        is_string_valid = True  # if input string is empty, empty string is valid

    print(is_string_valid)

else:
    print("Invalid arguments! Try: $ python file_name.py input_file.txt")
